CREATE SCHEMA IF NOT EXISTS msa AUTHORIZATION platform;
CREATE SCHEMA IF NOT EXISTS msb AUTHORIZATION platform;

CREATE TABLE IF NOT EXISTS msa.entity_a (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_a VARCHAR(160) NOT NULL
);

CREATE TABLE IF NOT EXISTS msb.entity_b (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_b VARCHAR(160) NOT NULL
);

CREATE TABLE IF NOT EXISTS msb.entity_b_entity_a (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_a_id INTEGER NOT NULL,
    entityb_id INTEGER REFERENCES msb.entity_b(id) ON DELETE CASCADE
);

INSERT INTO msa.entity_a (id, nombre_a)
VALUES
    (1, 'Ada Lovelace'),
    (2, 'Alan Turing'),
    (3, 'Grace Hopper')
ON CONFLICT (id) DO NOTHING;

INSERT INTO msb.entity_b (id, nombre_b)
VALUES
    (1, 'Arquitectura de Software'),
    (2, 'Sistemas Distribuidos'),
    (3, 'Computacion en la Nube')
ON CONFLICT (id) DO NOTHING;

INSERT INTO msb.entity_b_entity_a (id, entity_a_id, entityb_id)
VALUES
    (1, 1, 1),
    (2, 2, 2),
    (3, 3, 3)
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('msa.entity_a', 'id'), COALESCE(MAX(id), 1), true) FROM msa.entity_a;
SELECT setval(pg_get_serial_sequence('msb.entity_b', 'id'), COALESCE(MAX(id), 1), true) FROM msb.entity_b;
SELECT setval(pg_get_serial_sequence('msb.entity_b_entity_a', 'id'), COALESCE(MAX(id), 1), true) FROM msb.entity_b_entity_a;

